sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: quD8Xiou2RJ00+1YfBZeTdRaYy4pXz60/zd6PRZztJPsyV1CCqeY/K5ghaVcQGz8+E3k784U3pHou+xG1YLIFThuS8Cn0fdtQONcU1efTfTqmDf+gK6vTiXI8f1VhIkNgwWJMjr4x85g6g6Q/paVkz72ptYOhelEm+eX9LN46OIeBm+imH6cEmsNZHLMJdDA7nK3rXOX0yMr9BQy/bQH7IoSyws024ata7yCVhsOIW9gdlR1AdhPa3YwGR92z9n02q7FRPrg2lL2c4bDAUgBN/oHXOQv2AAQkGFxcjwIL2B+mm8AuFuGflrQmsxrpub5nVek//LwgWOMS8pLkrkb+oJ/1IWvMuO0n7sO5XlFtscikcBkE8D7E2+7pZB81lNzDzO5yTLZuehxp94bQ9HqDixztVCX2frc411jXZ7iQG/hEPw6YYt5jbs3U6bagJDXlU+F8IyQ6PzPHzO93h94faKj4XX5sT+GKR31hIOaParv6keSNXUVSJ3u2nsbK83mfoegnaUkpwVClCB55tuQjJsDhkI/gdN9OrBmXbcWXGEUY5zQkytObe6VFQRbMwSFPjs/iKhYhk8K15yFWSMLGKv+5aamQAgBJjXyQZYXPW7V2lvwsP3b4VIjRbjl0+xZvUGG1ed6IJaL0ygDUnrDz2smDnd+1yg/Ri2LLT85Wkw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Inside-of-the-Cup---Volume-02_5357
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy